export const data = [
  {
    id: 1,
    name: "Services Hospital Lahore",
    code: "SERV",
    hospital_type: "Government",
    tehsil_name: "Lahore City Tehsil",
    created_on: new Date(),
    updated_on: new Date(),
  },
  {
    id: 2,
    name: "Doctors Hospital",
    code: "DOCS",
    hospital_type: "Private",
    tehsil_name: "Lahore City Tehsil",
    created_on: new Date(),
    updated_on: new Date(),
  },
  {
    id: 3,
    name: "Rawalpindi International Hospital",
    code: "RAWI",
    hospital_type: "Private",
    tehsil_name: "Rawalpindi Tehsil",
    created_on: new Date(),
    updated_on: new Date(),
  },
  {
    id: 4,
    name: "Armed Forces Institute of Cardiology",
    code: "AFIC",
    hospital_type: "Government",
    tehsil_name: "Rawalpindi Tehsil",
    created_on: new Date(),
    updated_on: new Date(),
  },
  {
    id: 5,
    name: "Children Hospital Multan",
    code: "CHM",
    hospital_type: "Government",
    tehsil_name: "Multan City Tehsil",
    created_on: new Date(),
    updated_on: new Date(),
  },
  {
    id: 6,
    name: "St. Raphael's Hospital",
    code: "STRA",
    hospital_type: "Private",
    tehsil_name: "Faisalabad City Tehsil",
    created_on: new Date(),
    updated_on: new Date(),
  },
  {
    id: 7,
    name: "Abbassi Shaheed Hospital",
    code: "ASH",
    hospital_type: "Government",
    tehsil_name: "Karachi City Tehsil",
    created_on: new Date(),
    updated_on: new Date(),
  },
  {
    id: 8,
    name: "Aga Khan Hospital",
    code: "AKH",
    hospital_type: "Private",
    tehsil_name: "Karachi City Tehsil",
    created_on: new Date(),
    updated_on: new Date(),
  },
  {
    id: 9,
    name: "Liaquat University Hospital",
    code: "LUH",
    hospital_type: "Government",
    tehsil_name: "Hyderabad City Tehsil",
    created_on: new Date(),
    updated_on: new Date(),
  },
  {
    id: 10,
    name: "Hayatabad Medical Complex",
    code: "HMC",
    hospital_type: "Government",
    tehsil_name: "Peshawar City Tehsil",
    created_on: new Date(),
    updated_on: new Date(),
  },
  {
    id: 11,
    name: "Ayub Teaching Hospital",
    code: "ATH",
    hospital_type: "Government",
    tehsil_name: "Abbottabad City Tehsil",
    created_on: new Date(),
    updated_on: new Date(),
  },
  {
    id: 12,
    name: "Miangul Abdul Haq Jahanzeb Kidney Hospital",
    code: "MAH",
    hospital_type: "Government",
    tehsil_name: "Swat City Tehsil",
    created_on: new Date(),
    updated_on: new Date(),
  },
  {
    id: 13,
    name: "Khalifa Gul Nawaz Teaching Hospital",
    code: "KGN",
    hospital_type: "Government",
    tehsil_name: "Bannu City Tehsil",
    created_on: new Date(),
    updated_on: new Date(),
  },
  {
    id: 14,
    name: "DHQ Hospital Dera Ismail Khan",
    code: "DHQD",
    hospital_type: "Government",
    tehsil_name: "Dera Ismail Khan City Tehsil",
    created_on: new Date(),
    updated_on: new Date(),
  },
  {
    id: 15,
    name: "Liaquat National Hospital",
    code: "LNH",
    hospital_type: "Private",
    tehsil_name: "Karachi City Tehsil",
    created_on: new Date(),
    updated_on: new Date(),
  },
  {
    id: 16,
    name: "Holy Family Hospital",
    code: "HFH",
    hospital_type: "Government",
    tehsil_name: "Rawalpindi City Tehsil",
    created_on: new Date(),
    updated_on: new Date(),
  },
  {
    id: 17,
    name: "Nishtar Hospital",
    code: "NIS",
    hospital_type: "Government",
    tehsil_name: "Multan City Tehsil",
    created_on: new Date(),
    updated_on: new Date(),
  },
  {
    id: 18,
    name: "Allied Hospital",
    code: "ALH",
    hospital_type: "Government",
    tehsil_name: "Faisalabad City Tehsil",
    created_on: new Date(),
    updated_on: new Date(),
  },
  {
    id: 19,
    name: "Benazir Bhutto Hospital",
    code: "BBH",
    hospital_type: "Government",
    tehsil_name: "Rawalpindi City Tehsil",
    created_on: new Date(),
    updated_on: new Date(),
  },
  {
    id: 20,
    name: "Sindh Institute of Urology and Transplantation (SIUT)",
    code: "SIUT",
    hospital_type: "Government",
    tehsil_name: "Karachi City Tehsil",
    created_on: new Date(),
    updated_on: new Date(),
  },
];
